version: "3.4"
services:
  citycom_mv_api:
    tty: true
    image: "citycom_mv_api"
    stdin_open: true
    build:
      context: .
      target: "development"
    volumes:
      - ".:/citycom_mv_api"
    env_file: .env